function(add_test_target SRC)
    string(REGEX REPLACE "^.*test_(.*)\\.c$" "\\1" SUITE_NAME "${SRC}")
    if ("${SUITE_NAME}" STREQUAL "")
        message(FATAL_ERROR "SUITE_NAME is empty: SRC=${SRC}")
    endif()
    set(TARGET "gc.test.test_${SUITE_NAME}")
    add_executable(${TARGET} ${SRC})
    target_link_libraries(${TARGET} gc test_framework)
    add_test(NAME "gc/test/${SUITE_NAME}" COMMAND ${TARGET})
endfunction ()

set(SRCS test_hashmap.c test_gc.c)
foreach (SRC IN LISTS SRCS)
    add_test_target(${SRC})
endforeach ()
